### ISSUE TITLE
Missing device configuration: Aeotec MultiSensor 7

### ISSUE THREAD

**Issue by luzik** [AlCalzone/node-zwave-js#3885] opened 2021-12-11 18:33 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Aeotec MultiSensor 7

### Manufacturer ID

0x0371

### Product Type

0x0002

### Product ID

0x0018

### Firmware Version

1.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4061

**Comment by jmgiaever** [comment] 2021-12-11 18:43
Duplicate: https://github.com/zwave-js/node-zwave-js/issues/3853, edit: but the manufacturer id is different?

**Comment by AlCalzone** [comment] 2021-12-11 23:44
Duplicate of #3802

**Closed as completed** 2021-12-11 23:45 UTC
Labels: config ⚙
