### ISSUE TITLE
U-BOLT-PRO-ZWAVE door sensor status not working properly

### ISSUE THREAD

**Issue by tekkenly** [AlCalzone/node-zwave-js#5520] opened 2023-03-04 22:19 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I'm guessing it's a driver issue.

What do you observe?

u bolt z-wave was added successfully, everything works except the door sensor is always "unknown".
I tried to see some debug info, I found I can not see door sensor value update, but one of the "outsideHandlesCanOpenDoor" value changed according to door status. This lock have no outsidehandle, I guess that value should be door sensor value.

What did you expect to happen?

the door sensor should show correct value.

add this lock, the door sensor will naturally be "unknown".

I attached the value change log in text. and reinterview log as an attachment.

### Device information

Device info
U-BOLT-PRO-ZWAVE
by Ultraloq
Connected via [Z‐Stick Gen5 USB Controller](https://hass.tekken.one/config/devices/device/bdaf7ef3398e696e5ea603d089d34a35)
Firmware: 1.1.3
Z-Wave Info
ID: 9
Status: Alive
Ready: Yes
Highest security: S2 Access Control
Z-Wave Plus: Version 2

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Driver Version:
10.10.0
Server Version:
1.26.0

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

```
Subscribed to Z-Wave JS Log Messages…
Log Level changed to: Silly
2023-03-04T21:44:20.739Z SERIAL » 0x01150013090e9f03000076190af5caa27495924525c44d                    (23 bytes)
2023-03-04T21:44:20.753Z DRIVER » [Node 009] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      196
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 0
                                    └─[DoorLockCCOperationGet]
2023-03-04T21:44:20.762Z SERIAL « [ACK]                                                                   (0x06)
2023-03-04T21:44:20.768Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2023-03-04T21:44:20.772Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:44:20.777Z DRIVER « [RES] [SendData]
                                    was sent: true
2023-03-04T21:44:22.010Z SERIAL « 0x01180013c400007e00c17f7f7f7f0101030000000042040000ca              (26 bytes)
2023-03-04T21:44:22.016Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:44:22.024Z DRIVER « [REQ] [SendData]
                                    callback id:            196
                                    transmit status:        OK, took 1260 ms
                                    routing attempts:       4
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    ACK RSSI:               -63 dBm
                                    ACK channel no.:        1
                                    TX channel no.:         1
                                    beam:                   1000 ms
2023-03-04T21:44:22.039Z SERIAL « 0x011d00040009159f036c00c89276975b4b8a00d77af78ab09da5b11ec3001f    (31 bytes)
2023-03-04T21:44:22.045Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:44:22.050Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     currentMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.056Z CNTRLR   [Node 009] [~] [Door Lock] currentMode: 255 => 255                [Endpoint 0]
2023-03-04T21:44:22.060Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.065Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     targetMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.068Z CNTRLR   [Node 009] [~] [Door Lock] targetMode: 255 => 255                 [Endpoint 0]
2023-03-04T21:44:22.072Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.078Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     duration
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.081Z CNTRLR   [Node 009] [~] [Door Lock] duration: {"value":0,"unit":"seconds"} [Endpoint 0]
                                   => {"value":0,"unit":"seconds"}
2023-03-04T21:44:22.085Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.096Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     outsideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.100Z CNTRLR   [Node 009] [~] [Door Lock] outsideHandlesCanOpenDoor: false,false [Endpoint 0]
                                  ,false,false => false,false,false,false
2023-03-04T21:44:22.103Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.109Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     insideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.113Z CNTRLR   [Node 009] [~] [Door Lock] insideHandlesCanOpenDoor: false,false, [Endpoint 0]
                                  false,false => false,false,false,false
2023-03-04T21:44:22.116Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.122Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     boltStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.125Z CNTRLR   [Node 009] [~] [Door Lock] boltStatus: "locked" => "locked"       [Endpoint 0]
2023-03-04T21:44:22.129Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.137Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     latchStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:44:22.140Z CNTRLR   [Node 009] [~] [Door Lock] latchStatus: "open" => "open"          [Endpoint 0]
2023-03-04T21:44:22.143Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:44:22.152Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 108
                                    └─[DoorLockCCOperationReport]
                                        current mode:           Secured
                                        active outside handles: false, false, false, false
                                        active inside handles:  false, false, false, false
                                        latch status:           open
                                        bolt status:            locked
                                        door status:            open
                                        target mode:            Secured
                                        remaining duration:     0s
2023-03-04T21:49:26.718Z SERIAL « 0x0117000400090f9f036d00afc34112a049fc0edf46e2c30087                (25 bytes)
2023-03-04T21:49:26.727Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:49:26.733Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     level
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:49:26.739Z CNTRLR   [Node 009] [~] [Battery] level: 100 => 100                        [Endpoint 0]
2023-03-04T21:49:26.742Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:49:26.747Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     isLow
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:49:26.750Z CNTRLR   [Node 009] [~] [Battery] isLow: false => false                    [Endpoint 0]
2023-03-04T21:49:26.753Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:49:26.760Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 109
                                    └─[BatteryCCReport]
                                        level:  100
                                        is low: false
2023-03-04T21:54:31.922Z SERIAL « 0x0117000400090f9f036e0065d0f46cf46a57b09a61d0c100a6                (25 bytes)
2023-03-04T21:54:31.931Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:54:31.938Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     level
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:54:31.941Z CNTRLR   [Node 009] [~] [Battery] level: 100 => 100                        [Endpoint 0]
2023-03-04T21:54:31.944Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:54:31.950Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     isLow
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:54:31.953Z CNTRLR   [Node 009] [~] [Battery] isLow: false => false                    [Endpoint 0]
2023-03-04T21:54:31.956Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:54:31.962Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 110
                                    └─[BatteryCCReport]
                                        level:  100
                                        is low: false
2023-03-04T21:56:51.234Z SERIAL « 0x011d00040009159f036f005073d0aba0152c3028e0b5d651738890c5be0012    (31 bytes)
2023-03-04T21:56:51.244Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:56:51.251Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     currentMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.256Z CNTRLR   [Node 009] [~] [Door Lock] currentMode: 255 => 0                  [Endpoint 0]
2023-03-04T21:56:51.260Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.270Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     targetMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.274Z CNTRLR   [Node 009] [~] [Door Lock] targetMode: 255 => 0                   [Endpoint 0]
2023-03-04T21:56:51.280Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.288Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     duration
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.294Z CNTRLR   [Node 009] [~] [Door Lock] duration: {"value":0,"unit":"seconds"} [Endpoint 0]
                                   => {"value":0,"unit":"seconds"}
2023-03-04T21:56:51.299Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.312Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     outsideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.317Z CNTRLR   [Node 009] [~] [Door Lock] outsideHandlesCanOpenDoor: false,false [Endpoint 0]
                                  ,false,false => true,false,false,false
2023-03-04T21:56:51.322Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.331Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     insideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.336Z CNTRLR   [Node 009] [~] [Door Lock] insideHandlesCanOpenDoor: false,false, [Endpoint 0]
                                  false,false => false,false,false,false
2023-03-04T21:56:51.340Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.349Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     boltStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.355Z CNTRLR   [Node 009] [~] [Door Lock] boltStatus: "locked" => "unlocked"     [Endpoint 0]
2023-03-04T21:56:51.360Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.370Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     latchStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:51.376Z CNTRLR   [Node 009] [~] [Door Lock] latchStatus: "open" => "open"          [Endpoint 0]
2023-03-04T21:56:51.382Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:51.391Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 111
                                    └─[DoorLockCCOperationReport]
                                        current mode:           Unsecured
                                        active outside handles: true, false, false, false
                                        active inside handles:  false, false, false, false
                                        latch status:           open
                                        bolt status:            unlocked
                                        door status:            open
                                        target mode:            Unsecured
                                        remaining duration:     0s
2023-03-04T21:56:59.350Z SERIAL « 0x011d00040009159f037000c485f75fbb54eb7781d099950b529be295c300a7    (31 bytes)
2023-03-04T21:56:59.358Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:56:59.366Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     currentMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.370Z CNTRLR   [Node 009] [~] [Door Lock] currentMode: 0 => 255                  [Endpoint 0]
2023-03-04T21:56:59.373Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.381Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     targetMode
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.385Z CNTRLR   [Node 009] [~] [Door Lock] targetMode: 0 => 255                   [Endpoint 0]
2023-03-04T21:56:59.388Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.395Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     duration
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.399Z CNTRLR   [Node 009] [~] [Door Lock] duration: {"value":0,"unit":"seconds"} [Endpoint 0]
                                   => {"value":0,"unit":"seconds"}
2023-03-04T21:56:59.404Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.413Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     outsideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.418Z CNTRLR   [Node 009] [~] [Door Lock] outsideHandlesCanOpenDoor: true,false, [Endpoint 0]
                                  false,false => false,false,false,false
2023-03-04T21:56:59.423Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.433Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     insideHandlesCanOpenDoor
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.438Z CNTRLR   [Node 009] [~] [Door Lock] insideHandlesCanOpenDoor: false,false, [Endpoint 0]
                                  false,false => false,false,false,false
2023-03-04T21:56:59.443Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.455Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     boltStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.463Z CNTRLR   [Node 009] [~] [Door Lock] boltStatus: "unlocked" => "locked"     [Endpoint 0]
2023-03-04T21:56:59.474Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.496Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Door Lock
                                    endpoint:     0
                                    property:     latchStatus
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:56:59.501Z CNTRLR   [Node 009] [~] [Door Lock] latchStatus: "open" => "open"          [Endpoint 0]
2023-03-04T21:56:59.506Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       true
                                    should hide root values: false
2023-03-04T21:56:59.516Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 112
                                    └─[DoorLockCCOperationReport]
                                        current mode:           Secured
                                        active outside handles: false, false, false, false
                                        active inside handles:  false, false, false, false
                                        latch status:           open
                                        bolt status:            locked
                                        door status:            open
                                        target mode:            Secured
                                        remaining duration:     0s
2023-03-04T21:59:37.129Z SERIAL « 0x0117000400090f9f037100cf5407230dcc575581dca0c30045                (25 bytes)
2023-03-04T21:59:37.139Z SERIAL » [ACK]                                                                   (0x06)
2023-03-04T21:59:37.146Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     level
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:59:37.150Z CNTRLR   [Node 009] [~] [Battery] level: 100 => 100                        [Endpoint 0]
2023-03-04T21:59:37.153Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:59:37.160Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    commandClass: Battery
                                    endpoint:     0
                                    property:     isLow
                                    propertyKey:  undefined
                                    internal:     false
                                    secret:       false
                                    event source: undefined
2023-03-04T21:59:37.164Z CNTRLR   [Node 009] [~] [Battery] isLow: false => false                    [Endpoint 0]
2023-03-04T21:59:37.167Z CNTRLR   [Node 009] [translateValueEvent: value updated]
                                    is root endpoint:        true
                                    is application CC:       false
                                    should hide root values: false
2023-03-04T21:59:37.175Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 113
                                    └─[BatteryCCReport]
                                        level:  100
                                        is low: false

```

-----------------reinterview log--------------------------------------------

[zwave_js (2).log](https://github.com/zwave-js/node-zwave-js/files/10889786/zwave_js.2.log)

**Comment by AlCalzone** [comment] 2023-03-06 11:44
Duplicate of #5445

**Closed as not planned by AlCalzone** 2023-03-06 11:44 UTC
