### ISSUE TITLE
Missing device configuration: Yale (Assa Abloy) YRD450-ZW3

### ISSUE THREAD

**Issue by jasonkelly214** [AlCalzone/node-zwave-js#5777] opened 2023-05-09 01:44 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Yale (Assa Abloy) YRD450-ZW3 

### Manufacturer ID

0x0129

### Product Type

0x45d3

### Product ID

0x8104

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4794?selectedFrequencyId=-1

**Comment by AlCalzone** [comment] 2023-05-09 07:50
Duplicate of #5650

**Closed as not planned by AlCalzone** 2023-05-09 07:50 UTC
Labels: config ⚙
