### ISSUE TITLE
Aeotec Trisensor 8 ZWA045

### ISSUE THREAD

**Issue by Benneboy** [AlCalzone/node-zwave-js#7265] opened 2024-10-10 04:33 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Aeotec Trisensor 8

### Manufacturer ID

ZWA045

### Product Type

0x0002

### Product ID

0x002D

### Firmware Version

7.18.3

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/5016?selectedFrequencyId=1

**Comment by AlCalzone** [comment] 2024-10-30 09:07
Duplicate of #7200

**Closed as not planned by AlCalzone** 2024-10-30 09:07 UTC
Labels: config ⚙
