### ISSUE TITLE
Missing device configuration: DONEXON - varmo TZ eco

### ISSUE THREAD

**Issue by adamtyron** [AlCalzone/node-zwave-js#5384] opened 2023-01-31 10:47 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

DONEXON - varmo TZ eco

### Manufacturer ID

?

### Product Type

0x0003

### Product ID

0x0004

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/3328?selectedFrequencyId=-1

**Comment by AlCalzone** [comment] 2023-01-31 10:53
Duplicate of #5204

**Closed as not planned by AlCalzone** 2023-01-31 10:53 UTC
Labels: config ⚙

**Comment by AlCalzone** [comment] 2023-01-31 10:55
FWIW, this device was added in v10.5.2
