### ISSUE TITLE
Device (BE469ZP - 2 of them) Interview fails with timeouts and missing values.

### ISSUE THREAD

**Issue by CJOWood** [AlCalzone/node-zwave-js#4933] opened 2022-08-18 06:20 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

When I attempt to include the locks (through zwavejs2mqtt or zwavejs) they fail to interview completely, leaving parameters missing or values as undefined, including the User Code section (see image below).
![HASS Agent_HQUYXEbiEm](https://user-images.githubusercontent.com/2746295/185305469-90bb664b-8f55-4f86-ae1d-e12d3feebc55.png)

Looking at the logs shows many `Timed out while waiting for a response from the node (ZW0201)` errors throughout. Moving the lock within inches of the stick doesn't seem to make a difference.

Attempts to Re-Interview the device result in a loss of nearly all to all the information previously interviewed. Similar to  ([#1517](https://github.com/zwave-js/node-zwave-js/issues/1517)).

### Device information

Manufacturer: Schlage/Allegion
Model name: BE469ZP
Node ID in your network: 28

(I have 2 of these locks, both have the same issue. One is brand new. One is firmware version 11.0 and the other is version 10.4. Both devices behave the same way.)

Aeotec Z-Stick Gen 5 Plus (ZW090)

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
zwavejs2mqtt: 6.15.2
zwave-js: 9.6.2

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

This lock worked at a previous house but started developing issues after moving to a new house. It was excluded then began having issues when I tried to include it again. I was using zwavejs and was having issues there before moving to zwavejs2mqtt and experiencing the same issues.

### Attach Driver Logfile

[zwavejs_2022-08-17.log](https://github.com/zwave-js/node-zwave-js/files/9368065/zwavejs_2022-08-17.log)

**Comment by AlCalzone** [comment] 2022-08-22 11:13
Duplicate of #4918

**Closed as not planned by AlCalzone** 2022-08-22 11:13 UTC
