### ISSUE TITLE
Missing device configuration: Multisensor 7 - aeotec

### ISSUE THREAD

**Issue by Eliza1700** [AlCalzone/node-zwave-js#3929] opened 2021-12-19 08:13 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [ ] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Multisensor 7 - aeotec (ZWA024)

### Manufacturer ID

0x0371

### Product Type

0x02

### Product ID

0x018

### Firmware Version

1.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4088

### Do you have a manual?

https://help.aeotec.com/support/solutions/folders/6000237394

Id's found at https://help.aeotec.com/helpdesk/attachments/6121529483
Hope I got them right. Can't find them in the logs.

**Comment by AlCalzone** [comment] 2021-12-19 09:03
Duplicate of #3802

**Comment by AlCalzone** [comment] 2021-12-19 09:04
side note: the IDs you provided are plain wrong

**Closed as completed by AlCalzone** 2021-12-19 09:03 UTC
Labels: config ⚙

**Comment by Eliza1700** [comment] 2021-12-19 09:20
dude....come on.....I provided the links.
I have no idea where I can find the id's requested. As you are probably smatter and especially better experienced in these things I think you should be able to find the ID's needed. Or am I wrong? ;-)

**Comment by AlCalzone** [comment] 2021-12-19 12:03
I've answered to your email so you'll know the next time.
Nonetheless, just saying _"I don't know"_ is better than providing false information.

**Comment by Eliza1700** [comment] 2021-12-19 16:04
I changed the input, can we reopen this issue?

**Comment by AlCalzone** [comment] 2021-12-19 18:03
Why? It is a duplicate of another issue requesting the exact same device to be added.
