### ISSUE TITLE
Missing device configuration: Aeotec Multisensor 7

### ISSUE THREAD

**Issue by LarsMudde** [AlCalzone/node-zwave-js#3853] opened 2021-12-05 22:25 UTC
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Aeotec Multisensor 7

### Manufacturer ID

0x0086

### Product Type

0x0002

### Product ID

0x0018 

### Firmware Version

1.01

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4061?selectedFrequencyId=1

### Do you have a manual?

Please find the manual below:

https://help.aeotec.com/support/solutions/articles/6000232605-multisensor-7-user-guide

There's also a pdf version that has slightly more info at the bottom of the page, here's the link: https://help.aeotec.com/helpdesk/attachments/6124934520

Quick note: I'm not enturely sure about the manufacturer ID. I currently put it under AEON Labs, because that's what the Multisensor 6 is under. But I couldn't find it in my logs and on devices.zwave-js.io there's both Aeotec Ltd. and AEON Labs.

If you need any further help, assistance or logs (I'm still learning how to get them, this is my first Z-Wave device), don't hesitate to reach out to me. 

Regards,

Lars

**Comment by blhoward2** [comment] 2021-12-06 04:30
Duplicate of #3802

**Closed as completed by blhoward2** 2021-12-06 04:30 UTC
Labels: config ⚙
