### ISSUE TITLE
[bug] No configuration options on Haozee / Neocool cam Multisensor (but it exists on other devices)

### ISSUE THREAD

**Issue by Botched1** [AlCalzone/node-zwave-js#3649] opened 2021-11-03 00:07 UTC
### Version

**Checklist:**

- [x ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x ] I have checked the troubleshooting section and my problem is **not** described there.
- [x ] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x ] Docker

Zwavejs2Mqtt version: 5.10.1
Z-Wave JS version: 8.6.1

### Describe the bug
I have a Haozee (aka Neo Cool Cam) 5-in-1 Zwave 700 Multisensor. It works as expected, but there is no configuration section un der the device details to change configuration settings.

### To Reproduce
Paired device successfully with no security.

Open zwavejs2mqtt interface, and expand the device details, and there is no configuration section at all.

### Expected behavior
There should be a configuration section to change device configuration.

### Additional context
Screenshot:
![image](https://user-images.githubusercontent.com/19985320/139968468-fbbc87bf-d44d-426e-82b4-b63765c424c1.png)

![image](https://user-images.githubusercontent.com/19985320/139968302-04a1b989-e41a-4f71-a047-bbd542bd2e69.png)

**Comment by AlCalzone** [comment] 2021-11-03 10:32
Duplicate of #3646

**Comment by AlCalzone** [comment] 2021-11-03 10:32
Let's keep the discussion in the other issue.

**Closed as completed by AlCalzone** 2021-11-03 10:32 UTC
