### ISSUE TITLE
OTA Firmware update causes driver to become unresponsive

### ISSUE THREAD

**Issue by robarnold** [AlCalzone/node-zwave-js#6292] opened 2023-09-20 03:06 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Performing a firmware update on a node causes the driver to become unresponsive - I can no longer ping nodes or operate other devices on the network. Logs seem to show repeated failures to send. Workaround is to restart the container - ZUI/the driver refuse to soft reset during a firmware update.

### Device information

Manufacturer: Aeotec
Model name: ZWA037
Node ID in your network: 64

### How are you using `node-zwave-js`?

- [X] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`Home Assistant` branch: latest
`zwave-js-ui` branch: 8.25.1 (latest)

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

This version has worked with some but not all of this brand of device on my network. I haven't figured out a common pattern other than a general trend of "distance" - further away nodes tend to be more fickle. I think the fixes with #6260 helped with some of the devices I was trying to update (same models) but not all of them. This makes me think it's some kind of software/robustness issue somewhere in the zwave stack.

### Attach Driver Logfile

https://gist.github.com/robarnold/db6ed6a4dcd977b8816ccabe9eb16dfd

**Comment by AlCalzone** [comment] 2023-09-20 09:04
Seems to be another duplicate of https://github.com/zwave-js/node-zwave-js/issues/6260, again on firmware 7.19.3.
We may have to consider that version broken.

**Closed as not planned by AlCalzone** 2023-09-20 09:04 UTC
