### ISSUE TITLE
HomeSeer Technologies HS-FLS100+

### ISSUE THREAD

**Issue by vinmar1** [AlCalzone/node-zwave-js#3862] opened 2021-12-07 14:07 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Incorrect database entry

What do you observe?
The parameter selection for HomeSeer HS-FLS100+ is using the parameters for model HS-FLS100-G2, they are different parameter sets. The user manuals are correct though.

What did you expect to happen?
This does not allow for setting HS-FLS100+ parameters as I would like to.

  NA

Reference: https://github.com/home-assistant/core/issues/61061

### Device information

Manufacturer: HomeSeer
Model name: HS-FLS100+
Node ID in your network: NA

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.49

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[NA.txt](https://github.com/zwave-js/node-zwave-js/files/7668832/NA.txt)

**Comment by AlCalzone** [comment] 2021-12-07 14:12
Duplicate of #3701

**Closed as completed by AlCalzone** 2021-12-07 14:12 UTC
